sudo: false
language: python
python: 3.6
services:
- postgresql
addons:
  postgresql: "9.6"
env:
  global:
  - TEST_ARGS=""
  - secure: IAQoyAqW1pccRx1fqdnjJjh3iRe9l+rxU+OlQojvAqo4lcxdv6DkuVp4Rhvx2eiBXfdsZl7XrI2zCXHbVrUSbKL4RNnjv9ouJN/m29cUME+uwuTWOO+jY5g7bNdKOpeWvUZyhUR3FUdPdeh2sN7odsLF8XybV5uOdHdQSzK7R/Nf4XSYRgMsKLTNSq/MIBOD4goCpHT2etTe4P02HJxZ+a/ksv3DGI3cVgAcAzF8EDF0SFXauBZVYeffTl82lGSPRPVlUXdC7nBh8W9p49zJQEOhKq7rDMf5A3P8ZfoOVDBlsMGpqHJejezvR1c/GTDkenEWE8har4xwxvP/pJDfUrNKWjI79hdEpKcN2xOxAeobNAPJP4Ee33XCD6Q0spf7LePv3fNlERavqz0hNSIBrX4w2ueXBGh/hJr9fKtfDbcD7myRFe17X2vHEeiwzTGKkVVPqmaXRMg/1RgTHVFqhy2ayQpldvM+2d2Y9GO46CVr+Xf+CUdkOvNRd5tD9ur5s4L76GTJZlotGvZp0AIzgSa//wiX/ZGPTgN41NcDGnumbmfJ9nK11aCpq5elOaYunEKkiYzo1JSzNHxnoaa6lKLF3koRb7BUudHVxGsIUGMGTaXXjrMd1JF+RcISjija3YbzF//iheiTBJDbkl9TrMxVx0NFRG7SkG6jO0oHtcQ=
git:
  depth: 1
before_install:
- export PATH="$HOME/miniconda3/bin:$PATH"
- df -h
- pwd
- ls -a
- uname -a
- git --version
- git tag
install:
- ci/install_travis.sh
- source activate pudl
- ci/setup_postgres.sh
- export DISPLAY=":99.0"
- cd scripts
- python update_datastore.py --source ferc1 eia860 --years 2012 2016
- python update_datastore.py --source epacems states CO --years 2016
- python update_datastore.py --source eia923 --states CO --years 2016
- cd ..
script:
- pytest -sv $TEST_ARGS -m travis_ci
notifications:
  slack:
    secure: WuYtc2adpwG+EKxqIL2Hz1W8AL67/5HaILvQzEs7RM2+qUR+dvLroTdUl3nFTMYdvfaa6X+T4Loptjcpke3/0ZESynXegI3HL+KKOcDG6uoln6yEHM96WJ6uBjAR9Irkdx9NOBi1Py7SEDJ1LAOaxR1Z7re5UB6cZRQdCzsEIdcGmfb4aKAVLrowZiZmQKMlJXvd3LgSpGVhsCBV2msqBg0zz4ic5RYrCNNek/LN435sYgfzo2PN9wuVMarkR7plp925BVletqLcbL+0yrvLLxIAQrbWtF5vg0vlt8btps5PVf7DHkZYTBgjGHeayBcNGMgPHP3c4NAeU6t6VhwCY7rTHEI9HLwp8Qcd/pxLiDNq5csMz6yZ/1xmOreiHNAN48jxJefKGbeLUl9q9KLXuqrl+UuwEDJEcFFkpPKeCg0X2q3fk3mIighk0cfttAn42XXapd+TCplkwR7jiAnLr5S4F8nUpWirxCZeyO3YUS79RdtD1CZjdO/dB8bdzzp52puIq4GbkG8fVAQ5ZDGvWviEj5I194vylG0JQU5ohhDEM+alb8dc32euWbmsucjIiHH2Tr05UasLQbujEQaokVaHyBQEdSAvVyz1vScoKIJ4fxquGR0t5T0CbCvXumPxi8KmVK46oYo+23HJeHGIgzRD8XSoLsRW5DvnsXnQAdM=
