name: pudl
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage
  - coveralls
  - cython
  - dask
  - dbfread
  - fastparquet
  - jupyter
  - jupyterlab
  - matplotlib
  - nbval
  - networkx
  - numpy
  - pandas
  - pip
  - psycopg2
  - pyarrow
  - pytest
  - pytest-cov
  - python>=3.6
  - python-snappy
  - pyyaml
  - scikit-learn>=0.20
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sqlalchemy>=1.3.0
  - xlrd
  - xlsxwriter
  # conda-forge only:
  - timezonefinder
  - pip:
    - datapackage
    - goodtables
    - sqlalchemy-postgres-copy
    - tableschema
