name: pudl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - autopep8            # dev
  - bandit              # dev
  - coloredlogs         # base
  - conda>=4.7          # base conda 4.7 has universal "conda activate"
  - coverage            # dev
  - dask                # user
  - datapackage         # base
  - dbfread             # base
  - doc8                # dev
  - flake8              # dev
  - flake8-colors       # dev
  - flake8-docstrings   # dev
  - flake8-builtins     # dev
  - goodtables          # base
  - ipdb                # dev
  - isort               # dev
  - jupyter             # user
  - matplotlib          # user
  - nbval               # dev
  - networkx>=2.2       # base We depend on features introduced in v2.2
  - numpy               # base
  - pandas>=0.24        # base We depend on features introduced in 0.24
  - pandoc              # dev
  - pdbpp               # dev
  - pep8-naming         # dev
  - pip>=19.0           # N/A pip>=19.0 can do non-setuptools build
  - pre_commit          # dev
  - psycopg2            # base
  - pyarrow>=0.14.0     # base compilation issues below 0.14.0
  - pydocstyle=3.0.0    # dev v4.0.0 has a bug that breaks doc8 for now.
  - pytest              # dev
  - pytest-cov          # dev
  - python>=3.7         # N/A
  - python-snappy       # base
  - pyyaml              # base
  - scikit-learn>=0.20  # base pandas integration added in v0.20
  - scipy               # base
  - setuptools_scm      # dev
  - sphinx              # dev
  - sphinx_rtd_theme    # dev
  - sqlalchemy>=1.3.0   # base Security issues below v1.3.0
  - tableschema         # base
  - timezonefinder      # base
  - tox                 # dev
  - twine               # dev
  - xlsxwriter          # base
  - pip:
    - sqlalchemy-postgres-copy # base
