name: pudl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - autopep8            # dev
  - bandit              # dev
  - coloredlogs         # base
  - coverage            # dev
  - dask                # user
  - datapackage         # base
  - dbfread             # base
  - doc8                # dev
  - flake8              # dev
  - flake8-colors       # dev
  - flake8-docstrings   # dev
  - flake8-builtins     # dev
  - goodtables          # base
  - ipdb                # dev
  - isort               # dev
  - jupyter             # user
  - matplotlib          # user
  - nbval               # dev
  - networkx>=2.2       # base
  - numpy               # base
  - pandas>=0.24        # base
  - pandoc              # dev
  - pdbpp               # dev
  - pep8-naming         # dev
  - pip                 # N/A pip>=19.0 can do non-setuptools build
  - pre_commit          # dev
  - psycopg2            # base
  - pyarrow>=0.14.0     # base
  - pydocstyle=3.0.0    # dev
  - pytest              # dev
  - pytest-cov          # dev
  - python>=3.7         # N/A
  - python-snappy       # base
  - pyyaml              # base
  - scikit-learn>=0.20  # base
  - scipy               # base
  - setuptools_scm      # dev
  - sphinx              # dev
  - sphinx_rtd_theme    # dev
  - sqlalchemy>=1.3.0   # base
  - tableschema         # base
  - timezonefinder      # base
  - tox                 # dev
  - twine               # dev
  - xlsxwriter          # base
  - pip:
    - sqlalchemy-postgres-copy # base
    - tableschema-sql==1.0.1     # base
