name: pudl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - autopep8            # dev
  - bandit              # dev
  - codecov             # dev
  - coloredlogs
  - coverage            # dev
  - dask
  - datapackage
  - dbfread
  - flake8              # dev
  - goodtables
  - ipdb                # dev
  - isort               # dev
  - jupyter
  - jupyterlab
  - matplotlib
  - nbval               # dev
  - networkx>=2.2
  - numpy
  - pandas>=0.24
  - pandoc              # dev
  - pdbpp               # dev
  - pip
  - pre_commit          # dev
  - psycopg2
  - pyarrow>=0.14.0
  - pycodestyle         # dev
  - pydocstyle          # dev
  - pytest              # dev
  - pytest-cov          # dev
  - python>=3.7
  - python-snappy
  - pyyaml
  - scikit-learn>=0.20
  - scipy
  - setuptools_scm      # dev
  - sphinx              # dev
  - sphinx_rtd_theme    # dev
  - sqlalchemy>=1.3.0
  - tableschema
  - timezonefinder
  - tox                 # dev
  - xlsxwriter
  - pip:
    - sqlalchemy-postgres-copy
