name: pudl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - autopep8            # dev
  - bandit              # dev
  - codecov             # dev
  - coloredlogs         # base
  - coverage            # dev
  - dask                # user
  - datapackage         # base
  - dbfread             # base
  - flake8              # dev
  - goodtables          # base
  - ipdb                # dev
  - isort               # dev
  - jupyter             # user
  - jupyterlab          # user
  - matplotlib          # user
  - nbval               # dev
  - networkx>=2.2       # base
  - numpy               # base
  - pandas>=0.24        # base
  - pandoc              # dev
  - pdbpp               # dev
  - pip                 # N/A
  - pre_commit          # dev
  - psycopg2            # base
  - pyarrow>=0.14.0     # base
  - pycodestyle         # dev
  - pydocstyle          # dev
  - pytest              # dev
  - pytest-cov          # dev
  - python>=3.7         # N/A
  - python-snappy       # base
  - pyyaml              # base
  - scikit-learn>=0.20  # base
  - scipy               # base
  - setuptools_scm      # dev
  - sphinx              # dev
  - sphinx_rtd_theme    # dev
  - sqlalchemy>=1.3.0   # base
  - tableschema         # base
  - timezonefinder      # base
  - tox                 # dev
  - xlsxwriter          # base
  - pip:
    - sqlalchemy-postgres-copy # base
