name: pudl
channels:
  - defaults
dependencies:
  - cython =0.28.*
  - dbfread
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx =2.1.*
  - numpy =1.14.*
  - pandas =0.23.*
  - psycopg2 =2.7.*
  - pytest =3.5.*
  - python =3.6.*
  - scikit-learn =0.19.*
  - scipy =1.1.*
  - sqlalchemy =1.2.*
  - xlrd =1.1.*
  - xlsxwriter =1.0.*
  - pyyaml
  - pip:
    - datapackage
    - goodtables
    - sklearn-pandas
    - sqlalchemy-postgres-copy
