name: pudl
channels:
  - conda-forge
  - nodefaults
dependencies:
  - codecov
  - coloredlogs
  - coverage
  - dbfread
  - jupyter
  - jupyterlab
  - matplotlib
  - nbval
  - networkx>=2.2
  - numpy
  - pandas>=0.21
  - pip
  - psycopg2
  - pyarrow>=0.14.0
  - pytest
  - pytest-cov
  - python>=3.7
  - python-snappy
  - pyyaml
  - scikit-learn>=0.20
  - scipy
  - sqlalchemy>=1.3.0
  - tox
  - xlsxwriter
  - datapackage
  - goodtables
  - tableschema
  - timezonefinder
  - pip:
    - sqlalchemy-postgres-copy
