name: pudl
channels:
  - defaults
dependencies:
  - coverage
  - coveralls
  - cython
  - dask
  - dbfread
  - fastparquet
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - psycopg2
  - pyarrow
  - pylint
  - pytest
  - pytest-cov
  - python>=3.6
  - python-snappy
  - pyyaml
  - scikit-learn>=0.20
  - scipy
  - sqlalchemy>=1.2
  - xlrd
  - xlsxwriter
  - pip:
    - datapackage
    - goodtables
    - sqlalchemy-postgres-copy
    - tableschema
