name: pudl
channels:
  - defaults
dependencies:
  - coverage
  - coveralls
  - cython
  - dbfread
  - jupyter
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - pandas
  - psycopg2
  - pytest
  - pytest-cov
  - python
  - pyyaml
  - scikit-learn
  - scipy
  - sqlalchemy
  - xlrd
  - xlsxwriter
  - pip:
    - datapackage
    - goodtables
    - sqlalchemy-postgres-copy
